import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home({ data }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Client Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <img />
          <a href="/">Home</a>
          <a href="/services">Services</a>
          <a href="/about-us">About Us</a>
          <a href="/contact-us">Contact Us</a>
        </nav>
      </header>

      <main className={styles.main}>
        {data.map((ev) => (
          <a key={ev.id} href={`/services/${ev.id}`}>
            <Image width={300} height={200} alt={ev.title} src={ev.image} />
            <h2>{ev.title}</h2>
            <p>{ev.description}</p>
          </a>
        ))}
      </main>

      <footer className={styles.footer}>
        <p>© 2022 IT Global Professionals. All Rights Reserved.</p>
      </footer>
    </div>
  );
}

export async function getServerSideProps() {
  const { service_categories } = await import("/data/data.json");
  return {
    props: {
      data: service_categories,
    },
  };
}
